"""Generate a daily call sheet — Tyler's deliverable for phone-outreach mode.

Produces a markdown table he can pull up on his phone with:
  - business name
  - owner first name (if research surfaced one)
  - phone (formatted, click-to-call)
  - demo URL (live Vercel)
  - 3 talking points pulled from research (vibe, wow_facts, real_reviews snippets)
  - Google Maps link (so he can see the shop / drop a pin while on the call)

Output is markdown so Gmail renders it cleanly + Tyler can print it / read on phone.
"""
import json
import re
from datetime import date


def _format_phone(p):
    digits = re.sub(r'\D', '', p or '')
    if len(digits) >= 10:
        d = digits[-10:]
        return f'({d[:3]}) {d[3:6]}-{d[6:]}'
    return p or ''


def _talking_points(research):
    """Extract up to 3 punchy talking points from the research payload."""
    points = []
    if not research:
        return ['(no research data — call cold and ask about their setup)']
    # Years in business
    if research.get('years_in_business_claim'):
        points.append(f"{research['years_in_business_claim']} years in business")
    # Founded year (alternative)
    elif research.get('founded_year'):
        points.append(f"founded {research['founded_year']}")
    # Owner mention
    if research.get('owner_name') and research['owner_name'].lower() != 'unknown':
        if 'owner' not in ' '.join(points).lower():
            points.append(f"owner: {research['owner_name']}")
    # Vibe
    if research.get('vibe'):
        points.append(f"vibe: {research['vibe']}")
    # Wow facts
    for f in (research.get('wow_facts') or [])[:2]:
        if len(points) >= 4:
            break
        points.append(f)
    # Real review snippet (first one with text)
    reviews = research.get('real_reviews') or []
    for r in reviews[:1]:
        text = (r.get('text') or '').strip()
        if text and len(text) < 140:
            points.append(f'review: "{text}" — {r.get("author","?")}')
    return points[:4] if points else ['(call cold)']


def render_call_sheet(leads, today=None):
    """Returns markdown string. `leads` is a list of dicts from db.leads."""
    today = today or date.today().isoformat()
    n = len(leads)
    md = [
        f'# Call sheet — {today}',
        '',
        f'**{n} leads ready to call.** Demos are live, ring through and pitch.',
        '',
        '---',
        '',
    ]
    for i, lead in enumerate(leads, 1):
        research = {}
        if lead.get('research_payload'):
            try:
                research = json.loads(lead['research_payload'])
            except Exception:
                pass

        biz = lead.get('business_name') or '(no name)'
        phone_raw = lead.get('phone') or ''
        phone_disp = _format_phone(phone_raw)
        demo = lead.get('vercel_url') or '(demo not deployed)'
        gmaps = lead.get('google_maps_url') or ''
        owner_first = ''
        if research.get('owner_name') and research['owner_name'].lower() != 'unknown':
            owner_first = research['owner_name'].split()[0]
        rating = lead.get('rating')
        reviews = lead.get('reviews')
        rating_str = f"{rating}★ · {reviews} reviews" if rating else ''
        category = lead.get('category') or ''
        city = lead.get('city') or ''

        md.append(f'## {i}. {biz}')
        md.append('')
        if owner_first:
            md.append(f'**Ask for:** {owner_first}')
            md.append('')
        md.append(f'**Phone:** [{phone_disp}](tel:{phone_raw})')
        md.append('')
        md.append(f'**Demo:** {demo}')
        md.append('')
        if rating_str or category or city:
            bits = [b for b in [category, city, rating_str] if b]
            md.append(f'_{ " · ".join(bits) }_')
            md.append('')

        md.append('**Talking points:**')
        for tp in _talking_points(research):
            md.append(f'- {tp}')
        md.append('')

        if gmaps:
            md.append(f'[See on Google Maps]({gmaps})')
            md.append('')
        md.append('---')
        md.append('')

    md.append(f'_End of {today} sheet. Generated by atl-pipeline._')
    return '\n'.join(md)


def email_call_sheet(content_md, env, subject_suffix=None):
    """Email the markdown call sheet to Tyler via Resend.

    Resend renders markdown in plain-text emails fine; for richer formatting
    we also include the same content as text/html with <br> line breaks.
    """
    import os, requests
    api_key = env.get('RESEND_API_KEY') or os.environ.get('RESEND_API_KEY')
    to_email = env.get('RESEND_FROM_EMAIL') or os.environ.get('RESEND_FROM_EMAIL')
    if not (api_key and to_email):
        return None, {'error': 'Resend creds missing'}

    today = date.today().isoformat()
    subject = f'📞 Call sheet — {today}'
    if subject_suffix:
        subject += f' · {subject_suffix}'

    # Convert markdown to a basic HTML rendering (simple, no external lib)
    html = content_md
    html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'_(.+?)_', r'<em>\1</em>', html)
    html = re.sub(r'\[(.+?)\]\(([^)]+)\)', r'<a href="\2">\1</a>', html)
    html = html.replace('\n---\n', '\n<hr>\n')
    html = html.replace('\n', '<br>\n')

    payload = {
        'from': f'Nova Pipeline <{to_email}>',
        'to': [to_email],
        'subject': subject,
        'text': content_md,
        'html': f'<div style="font-family:-apple-system,sans-serif;line-height:1.5;max-width:680px">{html}</div>',
    }
    r = requests.post('https://api.resend.com/emails',
                      headers={'Authorization': f'Bearer {api_key}', 'Content-Type': 'application/json'},
                      json=payload, timeout=15)
    return r.status_code, r.json()
