"""Vercel serverless function source for the engagement tracker.

When a prospect opens their demo page, an embedded JS beacon hits
`/api/track` (this function) with the slug + event type. The function calls
Twilio to text Tyler the moment a hot signal fires (>=30s + >=50% scroll
in the same session OR >=2 pageviews from the same IP). De-duped per-slug
per-24h via Vercel KV (or a no-op fallback if KV isn't configured).

This file is written into the demos repo at `api/track.js` by
deploy.ensure_tracker_function(). Vercel auto-detects /api/*.js as a
serverless function — no extra config required.

Env vars expected on the demos Vercel project:
  TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM_NUMBER,
  TWILIO_NOTIFY_NUMBER   (Tyler's personal cell, for hot-lead alerts)

Optional:
  VERCEL_KV_REST_API_URL, VERCEL_KV_REST_API_TOKEN  (de-dup throttle)

The function source is kept here in the Python package so it ships with the
pipeline, gets version-controlled with the rest of the code, and the
deploy step writes it into the demos repo at push time.
"""

TRACK_JS = r'''// Auto-generated by atl_pipeline.deploy.ensure_tracker_function — do not hand-edit.
// Hot-lead engagement tracker for demo pages.

export default async function handler(req, res) {
  // Accept GET (image pixel) or POST (sendBeacon)
  const params = req.method === 'POST' ? (req.body || {}) : (req.query || {});
  const slug = (params.slug || '').toString().slice(0, 120);
  const event = (params.event || '').toString().slice(0, 40);
  const dwellMs = parseInt(params.dwell_ms || '0', 10);
  const scrollPct = parseInt(params.scroll_pct || '0', 10);

  // CORS + cache headers — these are tracking hits, never cacheable
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 'no-store, max-age=0');

  if (!slug || !event) {
    res.status(200).end();
    return;
  }

  // Hot signal threshold: visited AND meaningful engagement
  const isHot = (event === 'engaged') || (dwellMs >= 30000 && scrollPct >= 50);

  // De-dup: only one SMS per slug per 24h
  let shouldAlert = isHot;
  if (isHot && process.env.VERCEL_KV_REST_API_URL && process.env.VERCEL_KV_REST_API_TOKEN) {
    try {
      const key = `hot:${slug}`;
      const seen = await fetch(`${process.env.VERCEL_KV_REST_API_URL}/get/${encodeURIComponent(key)}`, {
        headers: { Authorization: `Bearer ${process.env.VERCEL_KV_REST_API_TOKEN}` },
      }).then(r => r.json()).catch(() => ({}));
      if (seen && seen.result) {
        shouldAlert = false;
      } else {
        await fetch(`${process.env.VERCEL_KV_REST_API_URL}/setex/${encodeURIComponent(key)}/86400/1`, {
          headers: { Authorization: `Bearer ${process.env.VERCEL_KV_REST_API_TOKEN}` },
        }).catch(() => {});
      }
    } catch (_) { /* fall through and alert anyway */ }
  }

  if (shouldAlert) {
    const sid = process.env.TWILIO_ACCOUNT_SID;
    const token = process.env.TWILIO_AUTH_TOKEN;
    const from = process.env.TWILIO_FROM_NUMBER;
    const to = process.env.TWILIO_NOTIFY_NUMBER;
    if (sid && token && from && to) {
      const detail = (event === 'engaged')
        ? `${Math.round(dwellMs / 1000)}s on page, ${scrollPct}% scroll`
        : 'opened demo';
      const body = `\u{1F525} HOT: ${slug} just ${detail}.`;
      const auth = Buffer.from(`${sid}:${token}`).toString('base64');
      try {
        await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`, {
          method: 'POST',
          headers: {
            Authorization: `Basic ${auth}`,
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          body: new URLSearchParams({ From: from, To: to, Body: body }).toString(),
        });
      } catch (_) { /* swallow — never break the page */ }
    }
  }

  res.status(200).end();
}
'''


# JS beacon that gets inlined into every demo page shell. Fires:
#  - one 'view' beacon on page load
#  - one 'engaged' beacon when (dwell >= 30s AND scroll >= 50%) is reached
#  - uses sendBeacon for the engaged event so it survives page unload
# Throttled client-side so a single session sends at most 2 beacons.
TRACKER_BEACON_JS = r'''<script>
(function(){
  try {
    var slug = location.pathname.split('/').filter(Boolean)[0] || location.hostname.split('.')[0];
    var origin = location.origin;
    var fired = { view: false, engaged: false };
    function send(event, extra) {
      if (fired[event]) return;
      fired[event] = true;
      var url = origin + '/api/track?slug=' + encodeURIComponent(slug) + '&event=' + event + (extra || '');
      try {
        if (navigator.sendBeacon) {
          navigator.sendBeacon(url);
        } else {
          var img = new Image(); img.src = url;
        }
      } catch (_) {}
    }
    // Fire 'view' immediately
    send('view');
    // Watch for engaged signal
    var start = Date.now();
    var maxScrollPct = 0;
    function onScroll() {
      var docH = document.documentElement.scrollHeight - window.innerHeight;
      if (docH <= 0) return;
      var pct = Math.min(100, Math.round((window.scrollY / docH) * 100));
      if (pct > maxScrollPct) maxScrollPct = pct;
      maybeFire();
    }
    function maybeFire() {
      if (fired.engaged) return;
      var dwell = Date.now() - start;
      if (dwell >= 30000 && maxScrollPct >= 50) {
        send('engaged', '&dwell_ms=' + dwell + '&scroll_pct=' + maxScrollPct);
      }
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    setInterval(maybeFire, 5000);
    // Also fire on unload if we hit the threshold late
    window.addEventListener('beforeunload', function(){
      if (!fired.engaged) {
        var dwell = Date.now() - start;
        if (dwell >= 20000 && maxScrollPct >= 30) {
          send('engaged', '&dwell_ms=' + dwell + '&scroll_pct=' + maxScrollPct);
        }
      }
    });
  } catch (_) {}
})();
</script>'''
